<?php

require_once __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\Person;
use App\Models\EmployeeRegistration;

$nomes = [
    'ADALTO GUADAGUINI','ADALTON ROSA ARAUJO','ADELITA SOARES BASTOS','ADEMIR ALVES','ADENILSON WAGNER FELIPE','ADILSON LOPES','ADRIANA LOPES DIAS SOUZA','ADRIANA OLIVEIRA DA SILVA','ADRIANO BERNARDINO ALVES','ADRIANO LACERDA DA SILVA','ADVANIA DA SILVA DOS REIS BATISTA','ALAIDE PIRES MOREIRA','ALBERTINO FERREIRA DA SILVA','ALDENICE MARIA ALMEIDA','ALESSANDRA APARECIDA SELEPENQUE CRUZ','ALESSANDRA MARIA ANDRADE DOS SANTOS RODRIGUES','ALEX SANDRO ALVES DE MIRANDA','ALEX SANDRO NOVAES','ALEXANDRE CARLOS DA SILVA','ALEXANDRE SURDI','ALI ANUAR CHEHADE','ALICE ODELON MOTTA','ALINE APARECIDA DE LIMA BENTO','ALINE DEBORA RAMOS FLAMIA','ALINE FRANCIELI DUARTE','ALINE LUCENA PRADO TIXILISKI','ALISSON RAIMUNDO DA SILVA','ALLINE EDUARDO CLEMENTE','ALVARO JOHNNY DE SOUZA ARAUJO','AMANDA BITTENCOURT RAMINELLI LEOACHI','AMANDA MASSAE KAMADA DA SILVA','AMARILDO APARECIDO CORREA','ANA KAROLINA GODOY ILMER SILVA','ANA LUCIA BARBOSA DOS SANTOS','ANA MARISA CANDIDO LOPES','ANA PAULA DEL ANHOL DE MELO','ANA PAULA DOS SANTOS BASTOS OLIVEIRA','ANA PAULA ZAMARIAM SILVA','ANADELIA ROSA GOUVEIA HASHIMOTO','ANDERSON ALMAGRO','ANDERSON CARLOS NOBREGA','ANDERSON PEREIRA DA SILVA','ANDERSON SIMAO','ANDREA LUZIA MIYAZAKI DA SILVA','ANDREA MANOEL LEONARDI','ANDREIA SABOIA MANOEL TEMISTOCLES','ANDREZA LIMA DE SOUZA','ANGELA CRISTINA LOPES DA SILVA','ANGELA MARIA PEREIRA ROSA','ANGELA MIDORI GOTO','ANGELA REGINA SILVA DIAS','ANGELA RODRIGUES DE LIMA SILVA','ANGELITA DA ROCHA DIAS SANCHEZ','ANGELUCY DA CUNHA MARQUES PEREIRA','ANITA BORGES CHEHADE','ANNA CAROLINE DA SILVA MANOEL','ANNE KAROLYNE VICENTE BIGNARDI','ANTONIO CEZAR TEIXEIRA','ANTONIO SANTANA CECILIO','APARECIDA CANDIDA DUARTE','BEATRIZ APARECIDA DOS SANTOS YNOUE','BEATRIZ PEDREIRA FERNANDES','BEATRIZ TAMURA KAZUMA','BERNARDETE APARECIDA CARVALHO TEMISTOCLES','BIANCA ARAUJO DA SILVA','BIANCA GISELI FRIZZO ADAMERUK','BIANCA RODRIGUES DOS ANJOS','BRUNA FERNANDA FERREIRA DA ROCHA','BRUNA NUNES RIBEIRO','BRUNA SUELI APARECIDA DOS SANTOS','BRUNO DA SILVA ALVES','BRUNO DOMINGOS DA SILVA','BRUNO GABRIEL RODRIGUES DE CAMPOS','BRUNO VIANA','CAIO GABRIEL CAETANO DE SALES','CAIRO KOGUISHI','CALIEL ALVES RAIMUNDO DA SILVA','CAMILA CRISTINA COSTA','CAMILA DA COSTA PESSOA','CAMILA GONCALVES CUSTODIO','CAMILO JOSE MACIEL WASILEWSKI','CAMYLA GAVIOLI CESTARIO','CARLISMAR CARLOS DA SILVA','CARLOS EDUARDO YAMADA','CAROLINE DA SILVA SANTOS','CAROLINE DEL ANHOL CAETANO','CAROLINE VAZ DE LIMA','CASSIA MARIA DA ROCHA','CASSIA SILVESTRE DO ESPÍRITO SANTO','CELIA CRISTINA GONCALVES','CELINA DITTRICH DE SIQUEIRA','CERIA MIEKO HASHIMOTO','CESAR FERREIRA RODRIGUES','CHAWELEN LUANA DE OLIVEIRA','CICERA MARCOLINO DE SIQUEIRA DA SILVA','CINTIA BONSANINO ALVES CASTOLDO','CINTIA DA SILVA LAURINDO','CINTYA MELLO DE SOUZA','CLAITON MENDES DA CONCEICAO','CLAUDENIR DIAS DOS SANTOS SILVA','CLAUDETE JOTA DOS SANTOS','CLAUDIA RODRIGUES GONCALVES SANTOS','CLAUDIA YOSHIKO TAKAHASHI NANAMI','CLAUDINEIA DOS SANTOS','CLAUDINES CRISTOVAM DE ALMEIDA','CLAUDINEY VICENTE DA SILVA','CLAUDIO ALVES DE LIMA','CLAUDIO GOMES LAURINDO','CLAUDIO ROBERTO PRUDENCIO','CLAUDIO SERGIO FARIAS','CLAUDIOMAR BRAZ DE ARRUDA','CLEITON FERREIRA DE SOUZA','CLEONICE DE SOUZA','CLEUNICE MENEZES SOUTO DA SILVA','CLEUNICE SANTOS DE OLIVEIRA DE ASSUNÇÃO','CONCEIÇÃO APARECIDA FRANCISCO GUADAGNIN DOS SANTOS','CRISTIANE APARECIDA GAIOSKI','CRISTIANE BATISTA ROSA','CRISTIANE CATARINA DE OLIVEIRA','CRISTIANE FERREIRA DE MELO','CRISTIANE TOZI BITTENCOURT FARIAS','CRISTIANI FERNANDES MIGUEL LOPES','CRISTINA APARECIDA DE SOUZA','CRISTINA CELIA TEIXEIRA ROSA','CRISTINA MOMESSO OTA DE OLIVEIRA','CRIZELENE DA SILVA CHAGAS','DAIANE CRISTINA DA SILVA TORQUATO','DAIANE DE SOUZA PINTO DUARTE','DAIANE SAYURI HATADA','DAIANE VILANI SILVA DO CARMO','DANIEL MAC DONALD VALERIANO MORAIS','DANIELA CRISTINA DA SILVA','DANIELE CRISTINA DA SILVA','DANIELE DE PAULA DA SILVA','DANIELE LEANDRO DA SILVA ANTUNES','DANIELE PAULA DA SILVA','DANIELLA LEIKA MIYABE','DANIELLI CRISTINA ROSENDO DOS SANTOS DA SILVA','DARCY SOUZA LACAL','DAWTON VALERIO DOS SANTOS','DAYANE CANAVERDE DE FARIAS SOUZA','DAYANE SIQUEIRA SILVA KOGUICHI','DAYNA ATANAZIO NUNES','DEIDY FERNANDA DE OLIVEIRA NASCIMENTO','DIANA DEL ANHOL DE MELO','DIAYR DE JESUS CAMARGO ARAUJO','DIONATAN PAIVA DIAS','DIRCEOMARA PEREIRA DA SILVA AMAOKA','DIVANILDO VALENTIN DE OLIVEIRA','DORALICE FERREIRA DE SOUZA','DOUGLAS CARVALHO DUARTE','DRIELI DE SOUZA','DUCINEIA PEREIRA ARAUJO DE OLIVEIRA','DULCINEIA OLERANOS COLHERI','DYLAN SILVA CUSTODIO','EDEILSON BORGES','EDENIL DE LIMA','EDIANA RODRIGUES SOUZA OLIVEIRA','EDILENI APARECIDA MIRA','EDNA FRANCISCO DAS NEVES','EDNA IZOLINA ALVES DE OLIVEIRA','EDNA MARIA DA SILVA','EDNA MIGUEL DA SILVA','EDNA PEREIRA DA SILVA','EDNA TIEMI UTIAMADA','EDNALVA DE SOUZA MENDES ALMEIDA','EDNEIA DE OLIVEIRA DAINEZI','EDSON KAZUO AMORIM INOUE','EDSON PRUDENCIO','EDUARDO ARAUJO BICHELINE','EDUARDO COSTA FURTADO','EDUARDO NOBREGA SIMOES','ELAINE AMARAL DE ARAUJO RAMOS','ELAINE CRISTINA BRAGA','ELENICE ALVES DE ARAUJO VALERIO','ELIANA ALVES DE SOUZA','ELIANA MAIA','ELIANE BARBOSA RIBEIRO','ELIANE DOS SANTOS RICARDO','ELIANE GOMES DE ARRUDA BARROS','ELIANE MESSIAS BORGES','ELISANGELA SOARES','ELIZABETH DA SILVA CAMARGO PEDROSO','ELIZADORA DE PAULA FIGUEREDO','ELLEN CRISTIANI TOMAS','ELTON JOHN DE ALMEIDA','ELTON LUIZ','ELTON YASUO TEIXEIRA BORGES','EMILENE SIENA DOS SANTOS','EMILIA TSUJI','EMILIO ALVES MARCONDES','ERICA FORIN KIKUTI','ERICA NOZAKI ZAMARIAM','ERICO HENRIQUE DA ROCHA','ERMENSON PEREIRA DA SILVA','ESTEFINI FRANSOARIS DOS SANTOS SOUTO','EUCLIDES TADEU DA SILVA','EVELIZE REGINA AIDA','EVERTON DOS SANTOS MORAES','FABIANA YUMI NOMURA BARBOSA','FABIANO RODRIGUES DE ALMEIDA','FABIO DE OLIVEIRA MONTEIRO','FABIO JUNIOR LEANDRO DA SILVA','FABIO LOURENÇO DA SILVA','FATIMA ALMEIDA DE JESUS','FERNANDA APARECIDA CABRAL DA SILVA SHIRATA','FERNANDA APARECIDA CAMPOS DA SILVA','FERNANDA DARCIN','FERNANDA DE MEDEIROS ANACLETO','FERNANDO DE SOUZA ALEXANDRE','FERNANDO FERNANDES RIBEIRO','FERNANDO HENRIQUE NUNES','FERNANDO MORAIS SANTANA','FERNANDO TEIXEIRA DA SILVA','FLAVIA DE JESUS NOGUEIRA DE LIMA','FLAVIO ANTUNES DE OLIVEIRA','FLAVIO LUIZ DUARTE','FLAVIO VALLINI','FLORISNI RODRIGUES DOS SANTOS LIMA','FRANCIELE SIMOES','GABRIEL ANTONIO SOARES SILVA','GABRIEL VICTOR GOTO','GENILDA CREVELARO BRANDEL','GENIVAL DE PAULA BEPPU','GEORGE TOSHIAKI HARA','GEOVANA OLIVEIRA DA SILVA','GEOVANE CANAVERDE DE FARIAS','GERALDO DE SOUZA','GIANI NAYARA DA CUNHA FRANCISCO','GILBERTO GIL DA SILVA','GIOVANNA LEANDRO DA SILVA CHEHADE','GISELE ALVES DA SILVA','GISELE MIYUKI TSUDA SHINOHATA','GISELE TEMISTOCLES RODRIGUES','GISLAINE ALINE DA CUNHA DOS SANTOS','GIZELI GOMES DE SOUZA','GLAUCIA RENATA MACIEL SPOSITO','GRACIELY RIBEIRO SOARES','GRAZIELE MAGALHAES','GRAZIELY FERREIRA DA SILVA','GREICE KELLY DE SOUZA','GREICI KELLY RIBEIRO DOS SANTOS','GUILHERME HITOMI AOKI','GUILHERME SENA DOS SANTOS CORREIA','HECTOR PABLO DEL ANHOL','HELENA COLHERI DA SILVA CICILIANO','HELENA DE ARAUJO HASSELMANN','HELENA GALVAO AMERICO DOS SANTOS','HELENO MARCAL SEGA DE ALMEIDA','HELIDA CRISTINA DO PRADO','HENRIQUE ZAMARIANO','IANI FAVARO CASAGRANDE','IDEVANILDO PIRES DE ALMEIDA','IGOR LIMA FREIRE OLIVEIRA','ILZA FELIX DE FIGUEIREDO DUARTE','IRACI DINIZ MACIEL','IRACILDA PAES DAS CHAGAS FERNANDES','IRANI HORTENCIO DOS SANTOS GAIOSKI','IRENE FUMIE UEKAWA CHIGAKI','IVANETE BALBINO DA SILVA','IVANIL IDA GOMES HARTMANN','IVETE RODRIGUES DOS SANTOS','IZAIAS CASTORINO','JANE DUARTE DOS SANTOS','JANICE DE SOUZA SILVA','JESSICA CHRISTINI DE ANDRADE CARNEIRO','JESSICA TEMISTOCLES RODRIGUES','JHENIFER CHISTINE SANTOS DA SILVA','JOABIS VALERIO','JOANA ALVES DE ANDRADE RODRIGUES','JOAO GUILHERME MOREIRA BUENO CARNEIRO','JOAO RICARDO SILVA RIBEIRO','JOCILENE BENTO PARRA','JOSE ALEXANDRE RAMOS SANTOS','JOSE CARLOS DOS REIS','JOSE FARIAS DOS SANTOS','JOSE MARIA DOS SANTOS','JOSEANE DOS SANTOS GASPARI','JOSEFA MARIA DE OLIVEIRA','JOSELY DE ALMEIDA BORGES','JOSIANE APARECIDA MARIA','JOSIANE APARECIDA SANTANA CHEFFER','JOSIANE DA SILVA DE ANDRADE','JOSIANE GOMES DE MORAES','JOSIANE LEPREVOSTI DUARTE','JOSIANE RIBEIRO DA SILVA','JOSIELLE JOSE SUTIL RIBEIRO','JOSIELLI POLIANI RAMALHO DA SILVA','JOSMEIRE LEITE DE SOUZA','JULIA HISSAKO WATANABE','JULIANA ALVES','JULIANA ASSIS MOREIRA MIGUEL','JULIANA FERREIRA DE SOUZA','JULIE GOUVEIA DA CRUZ','JULIO SEVERINO DA SILVA','JURANDIR FERREIRA DA SILVA','JUSSARA DE FATIMA RIBEIRO','KAREN DA SILVA SANTOS','KARINA AUGUSTO DOS SANTOS','KARINA MOLIN VICENTE','KATHIA LIRIA DA SILVA UMEMOTO','KATIA BUENO DE MORAES HARTMANN','KATIA FRANCISCO DOS SANTOS','KATYA HIROMI TAGO','KAWAN HARSHE KAKUBO','KEILA DENISE GONÇALVES DUARTE','KEILA LUMI SUGAHARA','KELLY ROMANA NERY NASCIMENTO','KEYLA MESSIAS DE SIQUEIRA DA SILVA','KLEBER WELLINGTON DUTRA DA SILVA','LAURA GOMES DA SILVA','LAURA TIEMI MIZUGUTI DA SILVA','LAYANNA CAROLINE FERNANDES BEBIANO VIEIRA','LEIA BALSANI FIGUEIREDO','LEIKA GIL DA SILVA','LEILA MARIA GOMES','LENITA GOMES DE SOUZA','LEONICE APARECIDA DE SANT ANA SILVA','LILIA KURUMI GOCHI SHIMIZU','LILIAM AMAOKA','LILIAM DOS SANTOS BORGES','LILIAN DALETE SIQUEIRA VIEIRA','LILIANE ALVES GUADAGNIN CALDEIRA','LINCON JOSE MIRANDA','LOREN STEPHANY FERREIRA SANCHEZ','LOURDES TAKACO AOYAGUI SHINOHATA','LUCAS PAES COSMOS','LUCAS SILVERIO DA SILVA','LUCELIA SUEIRO KATO','LUCIA GARCIA DA SILVA','LUCIANA CAMILA CORREA PEREIRA','LUCIANA DE OLIVEIRA','LUCIANA MAYUMI OKAMURA COSTA','LUCIANA PEREIRA DA SILVA BASTOS','LUCIANA RIBEIRO DOS SANTOS','LUCIANA SASSAZAWA BUENO RODRIGUES','LUCIANO JOSE FIDELIS','LUCIMARA PEREIRA','LUCINDO DE SOUZA MENESES','LUCINEIA GOMES DOS SANTOS','LUCINETE FERREIRA RODRIGUES GONCALVES','LUCY KIYOMI MATSUO FUSSUMA','LUCY MIDORI HAMA','LUDIMILA CRISTINA BATISTA DE CARVALHO DA SILVA','LUDMILLA LEANDRO RODRIGUES','LUIZ GOMES DOS SANTOS','LUIZ SERGIO TEIXEIRA','LUMA DUQUE BORTOLUZZI','LUZINETE ALVES','LUZINETE MARIA DA CONCEIÇÃO','LUZINETE ROSA DE CAMARGO OKAMURA','LYARA MESSIAS DE SIQUEIRA','MADALENA CAMARGO BITTENCOURT RAMINELLI','MAGNA APARECIDA LOPES DE OLIVEIRA','MARCELA RODRIGUES DE SOUZA SILVA','MARCELA VIEIRA ANTUNES','MARCELLA DIAS CARVALHO','MARCELO ALVES DOS SANTOS','MARCELO CABRAL DA SILVA','MARCELO DE SOUZA','MARCELO DOMINGOS DA SILVA','MARCELO EDUARDO DOS SANTOS','MARCELO FRANCISCO DE JESUS','MARCELO ROBERTO HENRIQUE DE OLIVEIRA','MARCIA APARECIDA FORIM LUIZ','MARCIA AZENHA LUIZ GOMES DOS SANTOS','MARCIA DIAS CARVALHO ALVES','MARCIA MITIE KOGA KOGUISHI','MARCIO FRANCISCO SOARES','MARCIO JOSE LOURENCO DA SILVA','MARCOS ABELHA PEREIRA','MARCOS ANTONIO DA SILVA','MARCOS ANTONIO GARCIA DA SILVA','MARCOS ANTONIO SILVESTRE','MARCOS APARECIDO ALVES','MARCOS APARECIDO MEDEIROS','MARCOS AURELIO VIEIRA','MARCOS DE JESUS','MARCOS EDUARDO MATTOS SILVA','MARCOS KOITY KATTO','MARCOS LOPES DA COSTA','MARGARETH CAROLINE FERREIRA DA SILVA','MARGARIDA DE FATIMA LOURENCO','MARI EMILIA MILITAO','MARIA APARECIDA DE ARAUJO','MARIA APARECIDA DE MATTOS','MARIA APARECIDA RIBEIRO DE CASTRO GOUVEIA','MARIA CAROLINA ALVES LUZ','MARIA CRISTINA CASTRO DUARTE DE SOUZA','MARIA DE FATIMA FERREIRA PEREIRA','MARIA DEJACIR DE LIMA','MARIA HELENA HENRIQUE MONTEIRO','MARIA IZABEL FERNANDES MARTINS','MARIA JOSE FERREIRA DOS SANTOS DA SILVA','MARIA LUCIA DA SILVA','MARIA ODETE DOS SANTOS','MARIA ONDINA RODRIGUES IZU','MARIA SELMA DOS SANTOS CORDEIRO','MARIANA DE SOUZA BENEDITO','MARIANA DINIZ DE SOUZA GOMES','MARIANA MILENE DO CARMO DA SILVA','MARIANA VALERIA LEONARDI','MARIANE YUKARI AMBO','MARIFLAN DOS SANTOS','MARILENE DA ROCHA PAULO NARCIZO','MARIO HENRIQUE DE MATTOS','MARISA CORDEIRO BAQUETA','MARISA LEITE DE SOUZA','MARIUZA APARECIDA MARCIDELI','MARIZA BRANDAO VIEIRA ARAUJO','MARLENE DAVID DE MORAES DOS SANTOS','MARLENE DE OLIVEIRA FERREIRA','MARLENE SUELI DO NASCIMENTO RODRIGUES','MARLI VALENTIM DE OLIVEIRA','MARTA MARIA ROSA DE SOUZA','MATHEUS RODRIGUES DE BARROS','MAURA LEANDRO DE SOUZA','MAURICIO MASSAYUKI GONDO','MAURO YOSHII','MAYARA ANDREA MAEDA','MESSIAS DE BARROS AUGUSTO','MICHEL ANGELO BOMTEMPO','MIQUELANGELA ROCHA MENDONCA SILVA','MIRACI MARIA ALVES MARQUES','MIRIAM CRISTINA PINTO LEITE','MISSAE ALICE OMORI','MOHAMED ANUAR CHEHADE','MONICA APARECIDA DE SOUZA','MONICA SANTOS DE SOUZA CRUZ','MURILO AUGUSTO MUTAMBA','MURILO BARRERA RODRIGUES','MURILO LEONARDI','MYRIAM REGINA SUMIKO YONEZAWA CALDEIRA','NADIR VIEIRA','NATALIA TATEWAKI','NELCI ROSA','NEUCELIA MELLO DA SILVA SANTOS','NILDA GONCALVES MATSUBARA','NILO RODRIGUES DE SOUZA','NILSE SHINOHATA MENEGAZZO','NILSON LEANDRO DA SILVA','ODAIR DE ASSIS E SILVA','ORLANDO DOS SANTOS JÚNIOR','ORLANDO MENEGAZZO FILHO','OSCAR FRANCISCO DAS NEVES','OSVALDO KAZUSHIGUE YANO','PALOMA DE OLIVEIRA ARAUJO','PAMELA FONSECA RIBAS GIUNTA','PATRICIA ALVES DA SILVA','PATRICIA APARECIDA BARBOSA','PATRICIA APARECIDA DE MORAES','PATRICIA BUENO PINHEIRO','PATRICIA TIEMI KIMURA','PATRICIA ZOTELLI SILVA','PAULA ROSIANE SOARES DE OLIVEIRA SILVA','PAULINO JOSE PAIVA','PAULO FERREIRA RODRIGUES','PAULO HENRIQUE BELLA','PAULO ROBERTO MOREIRA','PAULO SERGIO KUYA','PAULO SERGIO LOPES','PEDRO ELIAS BARBOSA NETO','RACHEL EDUARDO','RAFAEL GOUVEIA GRECA','RAIMUNDO CUSTODIO FILHO','REBECA MATOS ROCHA ORSAI','REGINA HONORIO DA SILVA','REGINA MARIA CUSTODIO COSTA','REGINA MARIA DA SILVA','REGINALDO ALVES ROCHA','REIZIELI DOS SANTOS GODOI','RENATA GOMES DA SILVA CAMARGO','RICARDO APARECIDO DA SILVA','RICARDO HENRIQUE DA CONCEICAO','RITA DE CASSIA ESCATAMBULO','RITA PAULA GALLASSI','ROBERTA SANTOS MORALES','ROBERTO FERNANDES PEREIRA','ROBSON BARBOSA','ROBSON FERREIRA SOARES','ROGERIO CUSTODIO','RONALDO SILVERIO','ROSANA LUCIA SOARES SILVA','ROSANA MARIA DE OLIVEIRA APRIGIO','ROSANA RODRIGUES LIMA','ROSANGELA ANDRADE DOS SANTOS','ROSANGELA APARECIDA DE OLIVEIRA GOMES','ROSANGELA JOSE DOS SANTOS','ROSANIA APARECIDA DA SILVA NAKANO','ROSEANE SANTOS','ROSELI JORDAO','ROSEMEIRE DOS SANTOS','ROSEVALDO CAMILO DA SILVA','ROSIMEIRY DA SILVA TRINDADE','ROSINEI RAVAGNANI RODRIGUES','ROSINEY CANDIDO','RUBIA RIBEIRO DE ASSIS','RUI VICENTE DA SILVA','RUTE MARIA DUARTE NEVES','SABRINA DE FATIMA QUANI FELIX RIBEIRO','SAMARA REGINA BASSO VIANA','SANDRA AMARO DA COSTA','SANDRA APARECIDA DE ALMEIDA FELIPE','SANDRA APARECIDA FLAMIA DA SILVA','SANDRA DOMINGUES DOS SANTOS','SANDRO COLHERI','SANDRO JOSE RODRIGUES','SEBASTIAO APARECIDO CASONI','SEBASTIAO RIBEIRO','SEBASTIAO TEOTONIO PEREIRA','SERGIO ALVES DE OLIVEIRA','SERGIO VARGAS','SHEILA REGINA TERRENAS','SIDINEI DOS SANTOS LOPES','SIDNEIA PEREIRA DE ARAUJO BRITO','SILMARA APARECIDA DOS SANTOS','SILVANA LAJARIN PEREIRA','SILVANA OLIVEIRA DOS SANTOS DA CONCEICAO','SILVANA RIBEIRO DA SILVA','SILVIA ANDREA PENEROTTI DIAS','SILVIA DOMINGUES DOS SANTOS','SILVIO KROL SOBRINHO','SIMONE DE LOURDES FORIN','SIMONE YUMI NAGATSUYU HORITA','SIRLENY MARTINS SILVERIO','SUELI BATISTA SILVA','SUELI MADALENA GARCIA','TAINARA DA SILVA FERREIRA','TALITA MEDEIROS DO PRADO','TAMARA TISSIANE DO NASCIMENTO GIULI TSUDA','TANIA MOREIRA VIANA DE LIMA','TATIANA BARBOSA DE PAULA','TATIANE AMARAL SANTANA OLIVEIRA','TATIANE BATISTA ROSA DA MOTA','TEREZA APARECIDA DE CARVALHO RODRIGUES','THAIS DOMINGUES DE SOUZA JACOB','THAIS DUTRA DA HORA','THAIS FERNANDA DE PAULA ANTUNES','THAMIRES FERNANDA DOS SANTOS','THAYANE FRANCE PEREIRA','TIAGO BRENO DA CONCEICAO','TIAGO GOMES LAURINDO','VALDECIR BARROS BERTO','VALDIRENE DE SOUZA COSTA','VALQUIRIA BUSTOLIN','VALQUIRIA FRANCISCA DE SOUZA','VALQUIRIA PEREIRA DIAS FAUSTINO','VANDA PEREIRA DA SILVA','VANESSA BARBOSA DE OLIVEIRA SILVA','VANESSA CARVALHO SATO','VANESSA FERNANDA SANCHES','VANESSA PEREIRA DA SILVA SIMÕES','VANESSA SILVA DO CARMO','VANESSA VALENTIM MACIEL','VANILDE RODRIGUES NORONHA','VERA LUCIA MANOEL LOURENCO','VERA LUCIA MIRANDA DOS SANTOS','VICTOR GABRIEL MOMESSO DE OLIVEIRA','VICTOR HUGO MARTELI GRACIONALI','VINICIUS ALDEBARAN DE OLIVEIRA GOMES','VIRGILINA DAS DORES COSTA AMARAL','VITOR FRANCISCO DA SILVA','VITOR HUGO FERNANDES DA SILVA','VITORIA EMANUELLY SILVA','VIVIANE DA SILVA','VIVIANE DE FATIMA CASTRO ROSIN','VIVIANE DE JESUS KICHELESKI','VIVIANE GONCALVES DE PAULA','VIVIANE MATEUS DA SILVA KOGA','VIVIANE PEDROSO','VIVIEN TOZI BITTENCOURT FANTINATI','WAGNER ARMANDO AMARAL DA SILVA','WALDIR GALDINO ROCHA','WALTER GONÇALVES','WANDA APARECIDA TEIXEIRA DA SILVA','WASHINGTON RAFAEL PROENÇA DA FONSECA','WEMYLLY MYLLENA DOS SANTOS','WILMA FERNANDES DE CASTRO DOS SANTOS','WILSON HIROSHI HASHIMOTO','WILSON JOSE DA SILVA','ZENAIDE PERPETUO CAMARGO','ZILDA OLIVEIRA SENA'
];

// Remove duplicados
$nomes = array_unique($nomes);
$totalNomes = count($nomes);

echo "=== VERIFICAÇÃO DE FUNCIONÁRIOS ===\n\n";
echo "Total de nomes únicos na lista: $totalNomes\n\n";

// Função para normalizar nomes (remover acentos)
function normalizeString($str) {
    $str = mb_strtoupper($str, 'UTF-8');
    $transliterator = Transliterator::create('NFD; [:Nonspacing Mark:] Remove; NFC');
    if ($transliterator) {
        $str = $transliterator->transliterate($str);
    }
    // Fallback para quando Intl não está disponível
    $str = strtr($str, [
        'Á'=>'A', 'À'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A',
        'É'=>'E', 'È'=>'E', 'Ê'=>'E', 'Ë'=>'E',
        'Í'=>'I', 'Ì'=>'I', 'Î'=>'I', 'Ï'=>'I',
        'Ó'=>'O', 'Ò'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O',
        'Ú'=>'U', 'Ù'=>'U', 'Û'=>'U', 'Ü'=>'U',
        'Ç'=>'C', 'Ñ'=>'N',
        'á'=>'a', 'à'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a',
        'é'=>'e', 'è'=>'e', 'ê'=>'e', 'ë'=>'e',
        'í'=>'i', 'ì'=>'i', 'î'=>'i', 'ï'=>'i',
        'ó'=>'o', 'ò'=>'o', 'ô'=>'o', 'õ'=>'o', 'ö'=>'o',
        'ú'=>'u', 'ù'=>'u', 'û'=>'u', 'ü'=>'u',
        'ç'=>'c', 'ñ'=>'n'
    ]);
    return trim($str);
}

// Carregar todas as pessoas do banco e criar índice normalizado
$todasPessoas = Person::with('employeeRegistrations')->get();
$indexNormalizado = [];
foreach ($todasPessoas as $pessoa) {
    $nomeNormalizado = normalizeString($pessoa->full_name);
    $indexNormalizado[$nomeNormalizado] = $pessoa;
}

$semCpf = [];
$semPis = [];
$semMatricula = [];
$naoEncontrados = [];

foreach ($nomes as $nome) {
    $nomeNormalizado = normalizeString($nome);
    
    $pessoa = $indexNormalizado[$nomeNormalizado] ?? null;
    
    if (!$pessoa) {
        $naoEncontrados[] = $nome;
        continue;
    }
    
    if (empty($pessoa->cpf)) {
        $semCpf[] = $nome;
    }
    
    if (empty($pessoa->pis_pasep)) {
        $semPis[] = $nome;
    }
    
    if ($pessoa->employeeRegistrations->isEmpty()) {
        $semMatricula[] = $nome;
    } else {
        $temMatricula = false;
        foreach ($pessoa->employeeRegistrations as $reg) {
            if (!empty($reg->matricula)) {
                $temMatricula = true;
                break;
            }
        }
        if (!$temMatricula) {
            $semMatricula[] = $nome;
        }
    }
}

$encontrados = $totalNomes - count($naoEncontrados);

echo "Funcionários encontrados no banco: $encontrados de $totalNomes\n\n";

echo "===========================================\n";
echo "NÃO ENCONTRADOS NO BANCO (" . count($naoEncontrados) . "):\n";
echo "===========================================\n";
foreach ($naoEncontrados as $nome) {
    echo "  ❌ $nome\n";
}

echo "\n===========================================\n";
echo "SEM CPF (" . count($semCpf) . "):\n";
echo "===========================================\n";
foreach ($semCpf as $nome) {
    echo "  ⚠️  $nome\n";
}

echo "\n===========================================\n";
echo "SEM PIS (" . count($semPis) . "):\n";
echo "===========================================\n";
foreach ($semPis as $nome) {
    echo "  ⚠️  $nome\n";
}

echo "\n===========================================\n";
echo "SEM MATRÍCULA (" . count($semMatricula) . "):\n";
echo "===========================================\n";
foreach ($semMatricula as $nome) {
    echo "  ⚠️  $nome\n";
}

echo "\n===========================================\n";
echo "RESUMO:\n";
echo "===========================================\n";
echo "Total na lista:        $totalNomes\n";
echo "Encontrados no banco:  $encontrados\n";
echo "Não encontrados:       " . count($naoEncontrados) . "\n";
echo "Sem CPF:               " . count($semCpf) . "\n";
echo "Sem PIS:               " . count($semPis) . "\n";
echo "Sem Matrícula:         " . count($semMatricula) . "\n";
echo "===========================================\n";
